version: 0.2
--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t test/blue-green ."
      - "docker tag test/blue-green test/blue-green:latest"

